services:
  postgres:
    image: postgres:16-alpine
    container_name: wedding_invitation_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedding_invitation
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wedding_invitation"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pg_data:

